### ISSUE TITLE
Missing Events

### ISSUE THREAD

**Issue by cmgraz** [ChrisMuir/MMA-Data-Scrape#1]
All of the below event #s are missing from the scrape:

225
207
204
198
196

It's 2 FX, 2 FUEL, and 1 FOX card.

**Comment by ChrisMuir** [comment]
Ah yes, those five events have given me issues in the past due to the fact that they don't have their own wiki page (they only exist on the generic "<yearXXXX> in UFC" pages). I will take a close look at this later tonight,

For now, can you confirm for me that you're using the latest version of the code files? If yes, can you run sessionInfo() and paste the output here?

Thanks!

**Comment by cmgraz** [comment]
I have have never used R and have limited programming experience in general.  It was a miracle I was able to figure out how to actually utilize these files.

With that said, I have no idea if this is what you're looking for, but here ya go.  I opened up the 0-ufc_bouts.RData workspace and ran sessionInfo() to get the follwing:

```R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

**Comment by cmgraz** [comment]
I just noticed.  The above mentioned events ARE actually scraped.  The issue is they're given the incorrect wikilinks and not following the event id trend, so I did not notice they were there.

They were all given the wikilink for UFC 149.

**Comment by ChrisMuir** [comment]
Hmm, yep just took a look and you are indeed correct about the wiki links being wrong. I will work on this some this weekend.

Thanks a bunch for bringing this to my attention....also, welcome to R and Github!

**Comment by ChrisMuir** [comment]
I've edited file 0-wiki_ufcbouts.R to account for this issue. I just reran the file from scratch and the issue seems to have been fixed. If you feel like testing the updated code file, let me know if it works for you.

**Comment by cmgraz** [comment]
Here are my results.   Not sure what to do from here:

```
> Loading required package: xml2
> 
> Attaching package: ‘dplyr’
> 
> The following objects are masked from ‘package:stats’:
> 
>     filter, lag
> 
> The following objects are masked from ‘package:base’:
> 
>     intersect, setdiff, setequal, union
> 
> Error: Table has inconsistent number of columns. Do you want fill = TRUE?
```

I'm not sure if it's because of the error, or if I'm doing something wrong, but the 0-ufc_bouts.RData is not being created in "~/mma_scrape/0-ufc_bouts.RData"

**Comment by cmgraz** [comment]
I'm still able to write to CSV however.  And I noticed it is missing exactly one completely random fight.

https://en.wikipedia.org/wiki/UFC_on_Fox:_Shogun_vs._Vera
Light Heavyweight	Phil Davis	Vs.	Wagner Prado	No Contest (accidental eye poke)	1	1:28

**Comment by ChrisMuir** [comment]
Thanks for the heads up, just ID'ed the issues and updated the code files.

**Comment by ChrisMuir** [comment]
I'm considering this issue closed. If anyone runs into any other instances of missing events, or events with incorrect Wikipedia links in the bouts dataframe, please feel free to open a new issue.
