### ISSUE TITLE
Eliminate championship tag

### ISSUE THREAD

**Issue by cmgraz** [ChrisMuir/MMA-Data-Scrape#2]
For this snippet of code:
```
# Eliminate all championship tags from strings within variables 
# FighterA, FighterB, and Belt.
id <- which(colnames(bouts) %in% c("FighterA", "FighterB", "Belt"))
bouts[, id] <- lapply(
  bouts[, id], function(x) 
    gsub(" \\(Fighter)| \\(c)| \\(ic)| \\(UFC Champion)| \\(Pride Champion)", 
         "", x, ignore.case = TRUE))
```
This isn't an issue (not sure where else to post), but I think the (c) tag can be useful as it's the only data we have to determine who went into the fight as champion.  This can then be turned into defining the potential difference between a title defense vs a title fight win.

I personally commented this out.  I then wrote to an .xls file, moved the (c) to their own column, and can now also track who the champions were entering the fight.

**Comment by ChrisMuir** [comment]
Yeah the concern you raised is one that I considered when developing this, but I didn't feel strongly about it either way. If that data is useful to you, then it may be to others as well, so I will work on this and try to spare the data as opposed to tossing it. Thanks for the feedback.

**Comment by ChrisMuir** [comment]
I've updated the way the championship and interim championship tags are handled within the bouts dataframe. Two feature variables are created within the df, one for each belt type. For any championship fights the name of the belt winner is appended to one of these two columns. The lineage of any specific belt can then be tracked by sorting the df by weight, then removing NA's within one of the two new variables.
